name: Angular GitHub CI
on:
  push:
    branches:
      - main
      
jobs:
  ci: 
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps: 
      - name: Checkout
      - uses: actions/checkout@v3.3.0
      
      - name: Setup Node.js environment
      - uses: actions/setup-node@v3.6.0
        with: 
          node-version:
            $
      
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3.2.4
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Install Dependencies
        if:
          steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build
        run: npm run build -- --prod

      - name: ESLint (JS/TS) Action 
        uses: iCrawl/action-eslint@v1
        
      - name: Test
        run: npm run test -- --prod
